# This is a two-step build:
# 1) Build the React app with Vite into a dist folder
# 2) Copy and serve the files with Nginx

# Use Alpine for smaller image
# Pin to minor version
FROM node:20.2-alpine AS build-deps

# Prevent Husky from installing git hooks
ENV HUSKY 0

# Change the working directory (other than /)
WORKDIR /usr/src/app

# Copy the files needed for installing dependencies (better layer caching)
COPY package.json yarn.lock ./

# Install dependencies using the yarn.lock file (reproduceable build)
RUN yarn install --frozen-lockfile

COPY . ./
RUN yarn build

# --------------------------------------

FROM nginx:1.24-alpine

COPY nginx.conf /etc/nginx/nginx.conf

# Copy the static files generated by Vite into nginx serving directory
COPY --from=build-deps /usr/src/app/dist /usr/share/nginx/html

# Indicate expected port
EXPOSE 80

# Tell Nginx to stay in the foreground (one container = one process)
CMD ["nginx", "-g", "daemon off;"]
